# Generated by Django 5.2.8 on 2025-12-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('store', 'Store'), ('collector', 'Collector'), ('subadmin', 'Sub-admin')], default='collector', max_length=20),
        ),
    ]
