# Generated by Django 5.2.8 on 2025-12-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('store', 'Store'), ('collector', 'Collector'), ('subadmin', 'Sub Admin'), ('user', 'User')], default='collector', max_length=20),
        ),
    ]
